### ISSUE TITLE
thank you for sharing ,  it seems has some mistake

### ISSUE THREAD

**Issue by yxpandjay** [ronghuautt/keras_DCNv2#1]
Exception has occurred: TypeError
unsupported operand type(s) for /: 'Dimension' and 'float'
  File "/home/modian/yeeee/server_sshfs/workspace_tf/project/Time/202009/my_centernet_keras/model/utils/layers.py", line 43, in build
    dtype = 'float32',
  File "/home/modian/yeeee/server_sshfs/workspace_tf/project/Time/202009/my_centernet_keras/model/nets/Resnet.py", line 44, in _build
    block = DCNv2(filter_num,3)(block)

my tensorflow=1.13.1
i use it like this:
output = DCNv2(filter_num,3)(block)
the block shape(h,w,c) is  (16 , 16 , 512 )

**Comment by RuaHU** [comment]
I have changed part of the code and tested it under Tensorflow=1.2.1 and Tensorflow=1.14.0. I can not reproduce your error, can you try the new code. If any error occurs, locate the error and tell me. I will fix it.

**Comment by yxpandjay** [comment]
i tested it again and found the error occurs when i change:

import keras.layers as KL

to:

import tensorflow.keras.layers as KL


it looks like there are some differences between keras and tf.keras

**Comment by yxpandjay** [comment]
i found the difference.
when i used tf.keras:

        testa = self.kernel_size + ( input_shape[-1]  , self.filters)
        testb = self.kernel_size + ( int(input_shape[-1])  , self.filters)
        print('testa', testa )
        print('testb', testb )

the output is:
testa (4, 4, Dimension(512), 256)
testb (4, 4, 512, 256)

so i change input_shape[-1] to int(input_shape[-1])  , it works in tf.keras

**Comment by RuaHU** [comment]
> i found the difference.
> when i used tf.keras:
> 
> ```
>     testa = self.kernel_size + ( input_shape[-1]  , self.filters)
>     testb = self.kernel_size + ( int(input_shape[-1])  , self.filters)
>     print('testa', testa )
>     print('testb', testb )
> ```
> 
> the output is:
> testa (4, 4, Dimension(512), 256)
> testb (4, 4, 512, 256)
> 
> so i change input_shape[-1] to int(input_shape[-1]) , it works in tf.keras

Yes, it seems the difference between tf.keras and keras causes this problem. I adjust the code, so it works for both. thanks for your feedback.
